# Generated by Django 4.1.7 on 2023-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_slag_firm_slug_rename_slag_person_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="skype",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="telegram",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="viber",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
