name: Code_checks
on: 
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]  

jobs: 
  build:
    runs-on: windows
    strategy:
      matrix: 
        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ maxrix.python-version }}
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ maxrix.python-version }}
      - name: Install debs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run isort
        run: isort .
      - name: Run black
        run: black .
      - name: Run flake8
        run: flake8 .
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html  
        