name: Code_checks
on: 
  push:
    branches: 
      - develop
  pull_request:
    branches: [develop, main]  

jobs: 
  build:
    runs-on: windows
    strategy:
      matrix: 
        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ maxrix.python-version }}
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ maxrix.python-version }}
      - name: Install debs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
