name: Python package
on: [push, pull_request]
jobs:
  run_unittests:
    run-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout repository code
      - uses: actions/checkout@v3  
      - name: Set up python ${{matrix.python-version}}  
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt    
      - name: Run isort
        run: isort .
      - name: Run black
        run: black .
      - name: Run flake8
        run: flake8 .
      - name: Run tests
        run: |
          cd ./practice_app/app
          python3 manage.py tests